### ISSUE TITLE
自分の知らない方法ですごい！

### ISSUE THREAD

**Issue by c0b21073** [c0b21149/ProjExD#1]
https://github.com/c0b21149/ProjExD/blob/adb43eeff3ac3bad09fba4585294ea9ecb0daeca/ex01/alphabet.py#L16
リストの要素を並べて出力する方法として自分の知らないものなので、すごいと思います！

**Comment by c0b21149** [comment]
言ってしまえば脳筋の力業です。コメントありがとうございます。
